const listings = [
    {
        id: 1,
        title: "Newly Renovated LA Bungalow",
        location: "Los Angeles, CA",
        neighborhood: "Highland Park",
        price: 3450,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Twin"],
        sqft: 950,
        laundry: "In-unit",
        parking: "1 car garage",
        pets: true,
        petPolicy: "Cats and small dogs allowed with deposit",
        utilities: "Water and trash included",
        amenities: ["WiFi", "Air Conditioning", "Dishwasher", "Washer/Dryer", "Hardwood Floors", "Private Patio", "Gas Stove"],
        description: "Beautifully renovated 1920s bungalow with original hardwood floors and modern updates. Features an open floor plan, updated kitchen with stainless steel appliances, and a private backyard patio. Perfect for professionals or small families.",
        availability: "Available Now",
        availableFrom: "2026-04-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/906956_1",
        images: [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 2,
        title: "1925 Spanish Cottage",
        location: "Los Angeles, CA",
        neighborhood: "Silver Lake",
        price: 4100,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["King", "Queen"],
        sqft: 1100,
        laundry: "In-unit",
        parking: "Driveway parking for 2 cars",
        pets: true,
        petPolicy: "Pet friendly with additional $500 deposit",
        utilities: "All utilities included",
        amenities: ["WiFi", "Central AC", "Dishwasher", "Washer/Dryer", "Original Tile Work", "Fireplace", "Garden", "Mountain Views"],
        description: "Charming 1925 Spanish cottage with original architectural details including arched doorways, decorative tile, and a beautiful wood-burning fireplace. Recently restored with modern amenities while preserving historic character. Lush garden and stunning views of the hills.",
        availability: "Available May 1",
        availableFrom: "2026-05-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/906052_1",
        images: [
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 3,
        title: "Hollywood Hills Retreat",
        location: "Los Angeles, CA",
        neighborhood: "Hollywood Hills",
        price: 3800,
        bedrooms: 1,
        bathrooms: 1,
        beds: ["King"],
        sqft: 850,
        laundry: "In-unit",
        parking: "1 car carport",
        pets: false,
        petPolicy: "No pets allowed",
        utilities: "Electric and gas not included",
        amenities: ["WiFi", "Air Conditioning", "Full Kitchen", "Washer/Dryer", "Hiking Trails Nearby", "City Views", "Deck"],
        description: "Peaceful hillside retreat with stunning city views. This modern studio-style 1BR features floor-to-ceiling windows, a chef's kitchen, and private deck. Steps from hiking trails and minutes from Hollywood attractions.",
        availability: "Available Now",
        availableFrom: "2026-03-15",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/939383_1",
        images: [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 4,
        title: "Quiet Cottage in Eagle Rock",
        location: "Los Angeles, CA",
        neighborhood: "Eagle Rock",
        price: 3500,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Full"],
        sqft: 900,
        laundry: "Shared",
        parking: "Street parking",
        pets: true,
        petPolicy: "One pet allowed under 25 lbs",
        utilities: "Water included",
        amenities: ["WiFi", "Window AC", "Full Kitchen", "Backyard Access", "Close to Restaurants", "Quiet Street"],
        description: "Cozy cottage in the heart of Eagle Rock, one of LA's most charming neighborhoods. Walking distance to Colorado Boulevard's shops and restaurants. Features a shared backyard with fruit trees and a peaceful, quiet atmosphere.",
        availability: "Available April 15",
        availableFrom: "2026-04-15",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/906446_1",
        images: [
            "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600573472591-ee6c563aaec5?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 5,
        title: "ModernHome Glendale",
        location: "Glendale, CA",
        neighborhood: "Adams Hill",
        price: 4000,
        bedrooms: 3,
        bathrooms: 2,
        beds: ["King", "Queen", "Twin"],
        sqft: 1400,
        laundry: "In-unit",
        parking: "2 car garage",
        pets: true,
        petPolicy: "Pets negotiable",
        utilities: "Not included",
        amenities: ["WiFi", "Central AC/Heat", "Modern Kitchen", "Washer/Dryer", "2 Car Garage", "Home Office", "Smart Home Features"],
        description: "Stunning modern home in desirable Adams Hill neighborhood. Open concept living with high ceilings, designer finishes, and a gourmet kitchen. Home office space, large backyard, and close to downtown Glendale shopping and dining.",
        availability: "Available June 1",
        availableFrom: "2026-06-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/792221_1",
        images: [
            "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566753104-685f4f24cb4d?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 6,
        title: "Mid-City Home with Backyard",
        location: "Los Angeles, CA",
        neighborhood: "Mid-City",
        price: 3750,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Queen"],
        sqft: 1050,
        laundry: "In-unit",
        parking: "1 car garage + driveway",
        pets: true,
        petPolicy: "Pet friendly yard",
        utilities: "Water and trash included",
        amenities: ["WiFi", "Central AC", "Full Kitchen", "Washer/Dryer", "Large Backyard", "BBQ Area", "Fruit Trees"],
        description: "Classic LA home with large private backyard in central Mid-City location. Perfect for entertaining with BBQ area and mature fruit trees. Easy access to the 10 freeway, close to museums, restaurants, and shopping.",
        availability: "Available Now",
        availableFrom: "2026-03-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/266234_1",
        images: [
            "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566752227-930223a5ec70?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566752547-33b279dbf9fb?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 7,
        title: "Jade Place West LA",
        location: "Los Angeles, CA",
        neighborhood: "West LA",
        price: 3950,
        bedrooms: 2,
        bathrooms: 2,
        beds: ["King", "Queen"],
        sqft: 1200,
        laundry: "In-unit",
        parking: "2 parking spaces",
        pets: false,
        petPolicy: "No pets allowed",
        utilities: "Not included",
        amenities: ["WiFi", "Central AC", "Modern Kitchen", "Washer/Dryer", "Balcony", "Pool Access", "Gym", "Secured Building"],
        description: "Luxury condo in secured West LA building with resort-style amenities. Features modern finishes, open floor plan, and private balcony. Building includes pool, fitness center, and 24-hour security. Walking distance to Westfield Century City.",
        availability: "Available May 15",
        availableFrom: "2026-05-15",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/543881_1",
        images: [
            "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566752734-2a0cd66c42f7?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154056-9e4cc9b1af17?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 8,
        title: "502 Rosemary Lane Burbank",
        location: "Burbank, CA",
        neighborhood: "Magnolia Park",
        price: 3900,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Twin"],
        sqft: 1000,
        laundry: "In-unit",
        parking: "Garage + driveway",
        pets: true,
        petPolicy: "Small pets OK with deposit",
        utilities: "Trash included",
        amenities: ["WiFi", "Central AC/Heat", "Updated Kitchen", "Washer/Dryer", "Private Yard", "Close to Studios", "Quiet Neighborhood"],
        description: "Charming Burbank home on tree-lined street near Magnolia Park. Perfect for entertainment industry professionals with easy studio access. Updated kitchen, private yard, and classic California bungalow charm.",
        availability: "Available April 1",
        availableFrom: "2026-04-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/912653_1",
        images: [
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 9,
        title: "NoHo Arts District Bungalow",
        location: "Los Angeles, CA",
        neighborhood: "North Hollywood",
        price: 3800,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Full"],
        sqft: 925,
        laundry: "In-unit",
        parking: "Carport",
        pets: true,
        petPolicy: "Pet friendly",
        utilities: "Water included",
        amenities: ["WiFi", "AC", "Full Kitchen", "Washer/Dryer", "Near Metro", "Walking Distance to Arts District", "Patio"],
        description: "Hip bungalow in the heart of NoHo Arts District. Steps from theaters, galleries, and the Metro Red Line. Features original charm with modern updates, private patio, and walkable neighborhood lifestyle.",
        availability: "Available Now",
        availableFrom: "2026-03-15",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/337012_1",
        images: [
            "https://images.unsplash.com/photo-1600047509782-20d39509f26d?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566752229-250ed79470f8?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 10,
        title: "Craftsman in Historic South Pasadena",
        location: "South Pasadena, CA",
        neighborhood: "Berkshire",
        price: 3950,
        bedrooms: 3,
        bathrooms: 1,
        beds: ["Queen", "Queen", "Twin"],
        sqft: 1250,
        laundry: "In-unit",
        parking: "Street parking",
        pets: true,
        petPolicy: "Pets allowed",
        utilities: "Water covered by owner, other utilities not included",
        amenities: ["WiFi", "Air Conditioning", "TV", "Dishwasher", "Washer/Dryer", "Balcony/Patio", "Garden", "Backyard"],
        description: "Ground level unit of a Craftsman duplex (available furnished or unfurnished). Located in the beautiful, historically protected Berkshire neighborhood, this recently updated home is filled with original details and tons of character. Conveniently located at the junction of South Pasadena, Los Angeles, and Alhambra - 5 minutes to charming downtown South Pas (and the gold line metro station), 10 minutes to the hip restaurants and shops of Highland Park, and 15 minutes to Downtown LA. A 100-year-old giant tortoise named Theo roams the yard.",
        availability: "Available July 1",
        availableFrom: "2026-07-01",
        minStay: "12 months",
        source: "SabbaticalHomes",
        url: "https://www.sabbaticalhomes.com/rental/165363",
        images: [
            "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 11,
        title: "Stylish Apartment Near UCLA Westwood",
        location: "Los Angeles, CA",
        neighborhood: "Westwood",
        price: 3950,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Queen"],
        sqft: 1000,
        laundry: "In-unit",
        parking: "Street parking",
        pets: true,
        petPolicy: "Pets allowed",
        utilities: "Not included",
        amenities: ["WiFi", "Air Conditioning", "TV", "Dishwasher", "Washer/Dryer", "Balcony/Patio", "Backyard"],
        description: "Welcome to your home away from home in the heart of Westwood. This beautifully furnished two-bedroom offers a peaceful retreat less than 1 mile from UCLA, making it the perfect choice for visiting scholars, professors, graduate students, or professionals seeking a quiet comfortable residence. Tucked away in a safe and serene residential neighborhood, with all the amenities that a big city has to offer just minutes away.",
        availability: "Available June 1",
        availableFrom: "2026-06-01",
        minStay: "1 month",
        source: "SabbaticalHomes",
        url: "https://www.sabbaticalhomes.com/rental/176195",
        images: [
            "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600573472591-ee6c563aaec5?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"
        ]
    },
    {
        id: 12,
        title: "Miracle Mile Architectural Gem",
        location: "Los Angeles, CA",
        neighborhood: "Miracle Mile",
        price: 4200,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Full", "Sofa Bed"],
        sqft: 1100,
        laundry: "In-unit",
        parking: "1 parking space",
        pets: false,
        petPolicy: "No pets",
        utilities: "Not included",
        amenities: ["WiFi", "Air Conditioning", "Full Kitchen", "Washer/Dryer", "Near LACMA", "Near The Grove", "Mid-Century Design"],
        description: "Stunning mid-century architectural gem in the heart of Miracle Mile. Walking distance to LACMA, the Academy Museum, and The Grove. Features original period details, designer furnishings, and a prime location for exploring LA's cultural offerings. Rated 4.84 stars by guests.",
        availability: "Check Airbnb for dates",
        availableFrom: "2026-04-01",
        source: "Airbnb",
        url: "https://www.airbnb.com/rooms/14342080",
        rating: 4.84,
        images: [
            "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=800&h=600&fit=crop",
            "https://images.unsplash.com/photo-1600585154056-9e4cc9b1af17?w=800&h=600&fit=crop"
        ]
    }
];
