window.listingsData = [
    {
        id: 1,
        title: "Newly Renovated LA Bungalow",
        location: "Los Angeles, CA",
        neighborhood: "Highland Park",
        price: 3450,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Twin"],
        sqft: 890,
        laundry: "In-unit",
        parking: "1 car garage",
        petsAllowed: true,
        petPolicy: "Cats and small dogs allowed with deposit",
        utilitiesIncluded: false,
        utilities: "Not included",
        amenities: ["WiFi", "Air Conditioning", "Dishwasher", "Washer/Dryer", "Hardwood Floors", "Private Patio", "Gas Stove", "Essentials (Kitchenware, Bathware, Linens)"],
        description: "Beautifully renovated 1920s bungalow with original hardwood floors and modern updates. Features an open floor plan, updated kitchen with stainless steel appliances, and a private backyard patio. 890 sq ft apartment in Los Angeles.",
        availability: "Available Now",
        availableFrom: "2026-03-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/906956_1",
        lat: 34.1119,
        lng: -118.1981,
        images: [
            "images/listing_1_img_1.jpg",
            "images/listing_1_img_2.jpg",
            "images/listing_1_img_3.jpg",
            "images/listing_1_img_4.jpg",
            "images/listing_1_img_5.jpg"
        ]
    },
    {
        id: 2,
        title: "1925 Spanish Cottage Nestled in Nature",
        location: "Los Angeles, CA",
        neighborhood: "Highland Park",
        price: 4100,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["King", "Queen"],
        sqft: 1100,
        laundry: "In-unit",
        parking: "Driveway parking for 2 cars",
        petsAllowed: true,
        petPolicy: "Pet friendly with additional deposit",
        utilitiesIncluded: true,
        utilities: "All utilities included",
        amenities: ["WiFi", "Central AC", "Dishwasher", "Washer/Dryer", "Original Tile Work", "Fireplace", "Garden", "Mountain Views"],
        description: "Charming 1925 Spanish cottage with original architectural details including arched doorways, decorative tile, and a beautiful wood-burning fireplace. Recently restored with modern amenities while preserving historic character. Lush garden and stunning views of the hills.",
        availability: "Available March 31",
        availableFrom: "2026-03-31",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/906052_1",
        lat: 34.1130,
        lng: -118.1960,
        images: [
            "images/listing_2_img_1.jpg",
            "images/listing_2_img_2.jpg",
            "images/listing_2_img_3.jpg",
            "images/listing_2_img_4.jpg"
        ]
    },
    {
        id: 3,
        title: "Hollywood Hills",
        location: "Los Angeles, CA",
        neighborhood: "Hollywood Hills",
        price: 3800,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "2x Bunk Beds"],
        sqft: 1200,
        laundry: "In-unit",
        parking: "1 car carport",
        petsAllowed: false,
        petPolicy: "No pets allowed",
        utilitiesIncluded: true,
        utilities: "Utilities included",
        amenities: ["WiFi", "Air Conditioning", "Full Kitchen", "Washer/Dryer", "Hiking Trails Nearby", "City Views", "Deck"],
        description: "Peaceful hillside retreat with stunning city views. This modern studio-style 1BR features floor-to-ceiling windows, a chef's kitchen, and private deck. Steps from hiking trails and minutes from Hollywood attractions.",
        availability: "Available May 31",
        availableFrom: "2026-05-31",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/939383_1",
        lat: 34.1176,
        lng: -118.3520,
        images: [
            "images/listing_3_img_1.jpeg",
            "images/listing_3_img_2.jpeg",
            "images/listing_3_img_3.jpeg",
            "images/listing_3_img_4.jpeg",
            "images/listing_3_img_5.jpeg"
        ]
    },
    {
        id: 4,
        title: "Quiet Cottage Near Hospitals and Colleges",
        location: "Los Angeles, CA",
        neighborhood: "Eagle Rock",
        price: 3500,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Full"],
        sqft: 900,
        laundry: "Shared",
        parking: "Street parking",
        petsAllowed: false,
        petPolicy: "No pets allowed",
        utilitiesIncluded: true,
        utilities: "Utilities included",
        amenities: ["WiFi", "Window AC", "Full Kitchen", "Backyard Access", "Close to Restaurants", "Quiet Street"],
        description: "Cozy cottage in the heart of Eagle Rock, one of LA's most charming neighborhoods. Walking distance to Colorado Boulevard's shops and restaurants. Near hospitals and colleges. Features a shared backyard with fruit trees and a peaceful, quiet atmosphere.",
        availability: "Available Now",
        availableFrom: "2026-03-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/906446_1",
        lat: 34.1396,
        lng: -118.2147,
        images: [
            "images/listing_4_img_1.jpg",
            "images/listing_4_img_2.jpg",
            "images/listing_4_img_3.jpg",
            "images/listing_4_img_4.jpg",
            "images/listing_4_img_5.jpg"
        ]
    },
    {
        id: 5,
        title: "ModernHome \u2013 Tesla Charger \u2013 Stay in LA",
        location: "Glendale, CA",
        neighborhood: "Riverside Rancho",
        price: 4000,
        bedrooms: 3,
        bathrooms: 2,
        beds: ["King", "Queen", "Twin"],
        sqft: 1400,
        laundry: "In-unit",
        parking: "2 car garage + Tesla charger",
        petsAllowed: false,
        petPolicy: "No pets allowed",
        utilitiesIncluded: true,
        utilities: "Utilities included",
        amenities: ["WiFi", "Central AC/Heat", "Modern Kitchen", "Washer/Dryer", "2 Car Garage", "Tesla Charger", "Home Office", "Smart Home Features"],
        description: "Stunning modern home in Riverside Rancho neighborhood of Glendale. Open concept living with high ceilings, designer finishes, and a gourmet kitchen. Home office space, Tesla charger, large backyard, and close to downtown Glendale shopping and dining.",
        availability: "Available April 13",
        availableFrom: "2026-04-13",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/792221_1",
        lat: 34.1525,
        lng: -118.2451,
        images: [
            "images/listing_5_img_1.png",
            "images/listing_5_img_2.png",
            "images/listing_5_img_3.png",
            "images/listing_5_img_4.png"
        ]
    },
    {
        id: 6,
        title: "Entire Unit w/ Backyard Under Wisteria Covered Pergola",
        location: "Los Angeles, CA",
        neighborhood: "Mid-City",
        price: 3750,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Queen"],
        sqft: 1050,
        laundry: "In-unit",
        parking: "1 car garage + driveway",
        petsAllowed: true,
        petPolicy: "Pet friendly yard",
        utilitiesIncluded: true,
        utilities: "Utilities included",
        amenities: ["WiFi", "Central AC", "Full Kitchen", "Washer/Dryer", "Large Backyard", "Wisteria Pergola", "BBQ Area", "Fruit Trees"],
        description: "Classic LA home with large private backyard featuring a wisteria-covered pergola in central Mid-City location. Perfect for entertaining with BBQ area and mature fruit trees. Easy access to the 10 freeway, close to museums, restaurants, and shopping.",
        availability: "Available Now",
        availableFrom: "2026-03-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/266234_1",
        lat: 34.0370,
        lng: -118.3440,
        images: [
            "images/listing_6_img_1.jpeg",
            "images/listing_6_img_2.jpeg",
            "images/listing_6_img_3.jpeg",
            "images/listing_6_img_4.jpg",
            "images/listing_6_img_5.jpeg"
        ]
    },
    {
        id: 7,
        title: "Jade Place \u2013 Charming West LA Triplex",
        location: "Los Angeles, CA",
        neighborhood: "Sawtelle / West LA",
        price: 3950,
        bedrooms: 2,
        bathrooms: 2,
        beds: ["King", "Queen"],
        sqft: 1200,
        laundry: "In-unit",
        parking: "2 parking spaces",
        petsAllowed: true,
        petPolicy: "Pets allowed (case-by-case)",
        utilitiesIncluded: true,
        utilities: "Utilities included",
        amenities: ["WiFi", "Central AC", "Modern Kitchen", "Washer/Dryer", "Balcony", "Pool Access", "Gym", "Secured Building"],
        description: "Charming triplex unit in the Sawtelle neighborhood of West LA. Features modern finishes, open floor plan, and private balcony. Walking distance to Sawtelle Japantown restaurants and Westfield Century City.",
        availability: "Available May 31",
        availableFrom: "2026-05-31",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/543881_1",
        lat: 34.0306,
        lng: -118.4634,
        images: [
            "images/listing_7_img_1.jpg",
            "images/listing_7_img_2.jpg",
            "images/listing_7_img_3.jpg",
            "images/listing_7_img_4.jpg",
            "images/listing_7_img_5.jpg"
        ]
    },
    {
        id: 8,
        title: "502 Rosemary Lane",
        location: "Burbank, CA",
        neighborhood: "Magnolia Park",
        price: 3900,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Twin"],
        sqft: 1000,
        laundry: "In-unit",
        parking: "Garage + driveway",
        petsAllowed: false,
        petPolicy: "No pets allowed",
        utilitiesIncluded: true,
        utilities: "Utilities included",
        amenities: ["WiFi", "Central AC/Heat", "Updated Kitchen", "Washer/Dryer", "Private Yard", "Close to Studios", "Quiet Neighborhood"],
        description: "Charming Burbank home on tree-lined street near Magnolia Park. Perfect for entertainment industry professionals with easy studio access. Updated kitchen, private yard, and classic California bungalow charm.",
        availability: "Available Now",
        availableFrom: "2026-03-01",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/912653_1",
        lat: 34.1678,
        lng: -118.3473,
        images: [
            "images/listing_8_img_1.jpg",
            "images/listing_8_img_2.jpg",
            "images/listing_8_img_3.jpg",
            "images/listing_8_img_4.jpg",
            "images/listing_8_img_5.jpg"
        ]
    },
    {
        id: 9,
        title: "NoHo Bungalow w/ CA Native Garden",
        location: "Los Angeles, CA",
        neighborhood: "North Hollywood",
        price: 3800,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Full"],
        sqft: 925,
        laundry: "In-unit",
        parking: "Carport",
        petsAllowed: true,
        petPolicy: "Pet friendly",
        utilitiesIncluded: true,
        utilities: "Utilities included",
        amenities: ["WiFi", "AC", "Full Kitchen", "Washer/Dryer", "Near Metro", "Walking Distance to Arts District", "CA Native Garden", "Patio"],
        description: "Hip bungalow in the heart of NoHo Arts District with a California native garden. Steps from theaters, galleries, and the Metro Red Line. Features original charm with modern updates, private patio, and walkable neighborhood lifestyle.",
        availability: "Available April 19",
        availableFrom: "2026-04-19",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/337012_1",
        lat: 34.1870,
        lng: -118.3813,
        images: [
            "images/listing_9_img_1.jpeg",
            "images/listing_9_img_2.jpeg",
            "images/listing_9_img_3.jpeg",
            "images/listing_9_img_4.jpeg"
        ]
    },
    {
        id: 10,
        title: "Charming 3 Bed + 1 Bath Craftsman in Historic Neighborhood",
        location: "South Pasadena, CA",
        neighborhood: "Berkshire, South Pasadena",
        price: 3950,
        bedrooms: 3,
        bathrooms: 1,
        beds: ["Queen", "Queen", "Twin"],
        sqft: 1250,
        laundry: "In-unit",
        parking: "Street parking",
        petsAllowed: true,
        petPolicy: "Pets allowed",
        utilitiesIncluded: false,
        utilities: "Water covered by owner, other utilities not included",
        amenities: ["WiFi", "Air Conditioning", "TV", "Dishwasher", "Washer/Dryer", "Balcony/Patio", "Garden", "Backyard"],
        description: "Ground level unit of a Craftsman duplex (available furnished or unfurnished). Located in the beautiful, historically protected Berkshire neighborhood, this recently updated home is filled with original details and tons of character. Conveniently located at the junction of South Pasadena, Los Angeles, and Alhambra - 5 minutes to charming downtown South Pas (and the gold line metro station), 10 minutes to the hip restaurants and shops of Highland Park, and 15 minutes to Downtown LA. A 100-year-old giant tortoise named Theo roams the yard.",
        availability: "Available July 1",
        availableFrom: "2026-07-01",
        minStay: "12 months",
        source: "SabbaticalHomes",
        url: "https://www.sabbaticalhomes.com/rental/165363",
        lat: 34.1161,
        lng: -118.1505,
        images: [
            "images/listing_10_img_1.jpg",
            "images/listing_10_img_2.jpeg",
            "images/listing_10_img_3.jpg",
            "images/listing_10_img_4.jpeg",
            "images/listing_10_img_5.jpg"
        ]
    },
    {
        id: 11,
        title: "Near UCLA \u2013 Stylish and Safe, Private Upscale 2-Bedroom Apartment",
        location: "Los Angeles, CA",
        neighborhood: "Westwood / Century City",
        price: 3950,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Queen"],
        sqft: 1000,
        laundry: "In-unit",
        parking: "Street parking",
        petsAllowed: true,
        petPolicy: "Pets allowed",
        utilitiesIncluded: false,
        utilities: "Not included (tenant pays utilities)",
        amenities: ["WiFi", "Air Conditioning", "TV", "Dishwasher", "Washer/Dryer", "Balcony/Patio", "Backyard"],
        description: "Welcome to your home away from home in the heart of Westwood. This beautifully furnished two-bedroom offers a peaceful retreat less than 1 mile from UCLA, making it the perfect choice for visiting scholars, professors, graduate students, or professionals seeking a quiet comfortable residence. Tucked away in a safe and serene residential neighborhood, with all the amenities that a big city has to offer just minutes away.",
        availability: "Available June 1",
        availableFrom: "2026-06-01",
        minStay: "1 month",
        source: "SabbaticalHomes",
        url: "https://www.sabbaticalhomes.com/rental/176195",
        lat: 34.0558,
        lng: -118.4218,
        images: [
            "images/listing_11_img_1.jpg",
            "images/listing_11_img_2.jpg",
            "images/listing_11_img_3.jpg",
            "images/listing_11_img_4.jpg",
            "images/listing_11_img_5.jpg"
        ]
    },
    {
        id: 12,
        title: "Best LA Location \u2013 Spacious Architectural Gem!",
        location: "Los Angeles, CA",
        neighborhood: "Miracle Mile / Longwood Highlands",
        price: 4100,
        bedrooms: 2,
        bathrooms: 1,
        beds: ["Queen", "Full", "Sofa Bed"],
        sqft: 1100,
        laundry: "In-unit",
        parking: "1 parking space",
        petsAllowed: true,
        petPolicy: "Dogs allowed, no cats",
        utilitiesIncluded: true,
        utilities: "Included in Airbnb rate",
        amenities: ["WiFi", "Air Conditioning", "Full Kitchen", "Washer/Dryer", "Near LACMA", "Near The Grove", "Mid-Century Design"],
        description: "Stunning mid-century architectural gem in the heart of Miracle Mile / Longwood Highlands. Walking distance to LACMA, the Academy Museum, and The Grove. Features original period details, designer furnishings, and a prime location for exploring LA's cultural offerings. Entire rental unit, 4 guests, 2 bedrooms, 3 beds, 1 bath. Rated 4.84 stars from 110 reviews.",
        availability: "Check Airbnb for dates",
        availableFrom: "2026-04-01",
        source: "Airbnb",
        url: "https://www.airbnb.com/rooms/14342080",
        rating: 4.84,
        lat: 34.0627,
        lng: -118.3553,
        images: [
            "images/listing_12_img_2.jpeg",
            "images/listing_12_img_3.jpg",
            "images/listing_12_img_4.jpeg",
            "images/listing_12_img_5.jpeg"
        ]
    },
    {
        id: 13,
        title: "Adorable 2 Bedroom Home in Glendale",
        location: "Glendale, CA",
        neighborhood: "Glendale (near The Americana)",
        price: 3600,
        bedrooms: 2,
        bathrooms: 2,
        beds: ["King", "Queen (Murphy bed)"],
        sqft: 860,
        laundry: "Shared on premises",
        parking: "Free parking on premises",
        petsAllowed: true,
        petPolicy: "Pets allowed ($1,000 refundable pet deposit)",
        utilitiesIncluded: true,
        utilities: "Utilities included",
        amenities: ["WiFi", "Air Conditioning", "Heating", "Full Kitchen", "Dishwasher", "Smart TV", "Washer/Dryer on Premises", "Dedicated Workspace", "Free Parking", "Backyard", "Hair Dryer"],
        description: "Great 2 bedroom home with an open kitchen. 2 OLED big screen TVs. The 2nd bedroom has a queen sized murphy bed that folds up for more space as an office. Nice shared backyard with a hammock. Quiet, clean, and safe neighborhood in the heart of Glendale. Walking distance from the Americana, Galleria, parks, great restaurants and bars. Close to Atwater Village, Silver Lake, Los Feliz, Burbank.",
        availability: "Available Now",
        availableFrom: "2026-03-22",
        source: "FurnishedFinder",
        url: "https://www.furnishedfinder.com/property/896482_1",
        lat: 34.1405,
        lng: -118.2402,
        images: [
            "images/listing_13_img_1.jpeg",
            "images/listing_13_img_2.jpeg",
            "images/listing_13_img_3.jpg",
            "images/listing_13_img_4.jpg",
            "images/listing_13_img_5.jpg"
        ]
    }
];
